-- ==============================================================================
-- PULSE PIPELINE — Database Bootstrap Script (init-db.sql)
-- ==============================================================================
-- This script is executed ONCE by the TimescaleDB container on first startup,
-- sourced from: /docker-entrypoint-initdb.d/01-init-db.sql
--
-- It runs as the superuser (POSTGRES_USER) against POSTGRES_DB.
--
-- DESIGN PRINCIPLES
-- -----------------
-- [MANDATE] Idempotent: All CREATE statements use IF NOT EXISTS or ON CONFLICT.
--   This allows the container to be destroyed and recreated without data loss
--   if the named volume is preserved.
-- [MANDATE — backend_schema.md] Creates the exact schema specified:
--   - ingested_events (primary analytics table, hypertable on created_at)
--   - dead_letter_queue (DLQ persistence table)
-- [MANDATE] B-Tree index on correlation_id for ON CONFLICT idempotency lookups.
-- [MANDATE] Time-series index on created_at for dashboard query performance.
-- [MANDATE — zero_trust_security.md] client_ip stored as a SHA-256 hash
--   (one-way, irreversible) — never stored as plaintext PII.
-- [MANDATE — operations_observability.md §2] Schema is additive-only and
--   forward/backward compatible for zero-downtime Alembic migrations.
-- ==============================================================================

-- --------------------------------------------------------------------------
-- EXTENSION BOOTSTRAP
-- --------------------------------------------------------------------------
-- Enable the TimescaleDB extension. This must run before hypertable creation.
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

-- Enable pgcrypto for SHA-256 hashing of PII fields (e.g., client_ip).
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- --------------------------------------------------------------------------
-- TABLE: ingested_events
-- --------------------------------------------------------------------------
-- Primary analytical table. Every accepted request that passes the Redis
-- Token Bucket rate limiter and is processed by a Celery worker lands here.
--
-- IDEMPOTENCY KEY: correlation_id (UUID)
--   Workers use ON CONFLICT (correlation_id) DO NOTHING to handle Kafka's
--   at-least-once delivery guarantee without creating duplicate rows.
--
-- TIME-SERIES: created_at (TIMESTAMPTZ)
--   This column is converted to the TimescaleDB hypertable partitioning
--   dimension, enabling sub-second time-range queries for the dashboard.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ingested_events (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type      VARCHAR(64) NOT NULL,
    status_code     INTEGER     NOT NULL,

    -- [MANDATE — backend_schema.md] JSONB payload for flexible event data.
    -- Pydantic strict models (extra="forbid") ensure only valid keys reach here.
    payload         JSONB       NOT NULL DEFAULT '{}',

    -- [MANDATE — backend_schema.md] Unique business key for idempotency.
    -- Maps directly to the X-Correlation-ID generated by the FastAPI gateway.
    correlation_id  UUID        NOT NULL,

    -- [MANDATE — zero_trust_security.md] PII field: client_ip is stored as
    -- a one-way SHA-256 hex digest. Never stored as plaintext.
    -- Format: encode(digest(ip_string, 'sha256'), 'hex')
    client_ip_hash  CHAR(64)    NULL,

    -- [MANDATE — backend_schema.md] Time-series dimension for hypertable.
    -- Workers must provide this value from the Kafka event timestamp, not
    -- from the worker container's local clock (per clock drift mandates).
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------------
-- CONVERT TO TIMESCALEDB HYPERTABLE
-- --------------------------------------------------------------------------
-- Partitions the ingested_events table by created_at into 7-day chunks.
-- This dramatically speeds up time-range queries for the audit dashboard.
-- The IF NOT EXISTS flag makes this idempotent on re-runs.
SELECT create_hypertable(
    'ingested_events',
    'created_at',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE
);

-- --------------------------------------------------------------------------
-- INDEXES: ingested_events
-- --------------------------------------------------------------------------

-- [MANDATE — backend_schema.md] B-Tree index on correlation_id.
-- Required for the ON CONFLICT (correlation_id) DO NOTHING constraint.
-- Must be UNIQUE to enforce the idempotency guarantee at the DB level.
CREATE UNIQUE INDEX IF NOT EXISTS idx_ingested_events_correlation_id
    ON ingested_events (correlation_id);

-- [MANDATE — backend_schema.md] Index on event_type for filtered queries
-- on the audit dashboard (e.g., "show only BLOCKED events").
CREATE INDEX IF NOT EXISTS idx_ingested_events_event_type
    ON ingested_events (event_type);

-- [MANDATE — backend_schema.md] Index on status_code for error rate queries.
CREATE INDEX IF NOT EXISTS idx_ingested_events_status_code
    ON ingested_events (status_code);

-- TimescaleDB automatically creates an index on created_at via the hypertable;
-- no manual index is required for the time dimension.

-- --------------------------------------------------------------------------
-- TABLE: dead_letter_queue
-- --------------------------------------------------------------------------
-- Resilience persistence table. Payloads that fail due to:
--   - External API quota exhaustion (402/403)
--   - Circuit breaker OPEN state
--   - Unrecoverable Celery worker errors
-- are routed here for manual admin replay at the next billing cycle.
--
-- [MANDATE — api_resilience_mandates.md §3] This table is the database-side
-- mirror of the Kafka `pulse.events.dlq` topic. Workers that consume from
-- the DLQ topic write a row here for persistent tracking and UI display.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dead_letter_queue (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The original Kafka event ID / X-Correlation-ID for audit trail linkage.
    correlation_id  UUID        NOT NULL,

    -- The raw event payload that could not be processed. Stored as JSONB for
    -- structural querying by the admin dashboard.
    failed_payload  JSONB       NOT NULL DEFAULT '{}',

    -- Human-readable error context: exception type, message, HTTP status code.
    -- Example: "CircuitBreakerError: OPEN after 5 consecutive 403 responses"
    error_reason    TEXT        NOT NULL,

    -- The Kafka topic the message originated from.
    source_topic    VARCHAR(256) NULL DEFAULT 'pulse.events.raw',

    -- Timestamp of the failed processing attempt.
    attempted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- [MANDATE — backend_schema.md] Replay tracking flag.
    -- Admin sets resolved=TRUE after manual replay or investigation.
    resolved        BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Timestamp when an admin marked the record as resolved.
    resolved_at     TIMESTAMPTZ NULL
);

-- --------------------------------------------------------------------------
-- INDEXES: dead_letter_queue
-- --------------------------------------------------------------------------

-- Index for correlation_id lookups (linking DLQ entry to original event).
CREATE INDEX IF NOT EXISTS idx_dlq_correlation_id
    ON dead_letter_queue (correlation_id);

-- Index for filtering unresolved events on the admin dashboard.
CREATE INDEX IF NOT EXISTS idx_dlq_resolved
    ON dead_letter_queue (resolved)
    WHERE resolved = FALSE;

-- Index for time-ordered DLQ audit queries.
CREATE INDEX IF NOT EXISTS idx_dlq_attempted_at
    ON dead_letter_queue (attempted_at DESC);

-- --------------------------------------------------------------------------
-- COMMENTS (documentation embedded in schema)
-- --------------------------------------------------------------------------
COMMENT ON TABLE ingested_events IS
    'Primary time-series analytics table. All accepted events that survive '
    'Redis Token Bucket rate limiting and are processed by Celery workers. '
    'Idempotency enforced via UNIQUE constraint on correlation_id. '
    'TimescaleDB hypertable partitioned by created_at (7-day chunks).';

COMMENT ON TABLE dead_letter_queue IS
    'Resilience persistence for unprocessable payloads. Populated by Celery '
    'workers when an event fails due to external API quota exhaustion, circuit '
    'breaker OPEN state, or permanent processing errors. Admin replay table.';

COMMENT ON COLUMN ingested_events.correlation_id IS
    'X-Correlation-ID generated by the FastAPI gateway. Serves as the unique '
    'business key for idempotent Kafka at-least-once delivery deduplication.';

COMMENT ON COLUMN ingested_events.client_ip_hash IS
    'One-way SHA-256 hash of the client IP address. Never stored as plaintext. '
    'Complies with data masking mandates (zero_trust_security.md §5).';

-- --------------------------------------------------------------------------
-- VERIFICATION QUERY (output visible in container startup logs)
-- --------------------------------------------------------------------------
DO $$
BEGIN
    RAISE NOTICE '==> [pulse-init-db] Schema bootstrap complete.';
    RAISE NOTICE '==> Tables: ingested_events (hypertable), dead_letter_queue';
    RAISE NOTICE '==> Extensions: timescaledb, pgcrypto';
END $$;
